name: Build and Test GNU Mach

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [i686, x86_64]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake libtool \
          gcc-multilib g++-multilib \
          texinfo \
          cppcheck \
          clang clang-tools \
          build-essential binutils binutils-multiarch \
          pkg-config gawk bison flex nasm \
          git python3
        # MIG from distro if available; otherwise build with mach headers
        if ! sudo apt-get install -y mig; then
          sudo apt-get install -y texinfo
          # Set up mach headers for MIG build
          sudo mkdir -p /usr/include/mach
          sudo cp -r include/mach/* /usr/include/mach/
          sudo ln -sf $(pwd)/i386/include/mach/i386 /usr/include/mach/machine
          # Build MIG from source
          git clone https://github.com/Unicorn-Forest/mig.git
          pushd mig
          autoreconf --install
          ./configure
          make -j$(nproc)
          sudo make install
          popd
        fi
    
    - name: Configure for ${{ matrix.arch }}
      run: |
        autoreconf --install
        mkdir build-${{ matrix.arch }}
        cd build-${{ matrix.arch }}
        ../configure --host=${{ matrix.arch }}-gnu MIG='mig'
    
    - name: Build
      run: |
        cd build-${{ matrix.arch }}
        make -j$(nproc)
    
    - name: Run static analysis
      run: |
        ./scripts/run-static-analysis.sh || true
        
    - name: Upload analysis reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: analysis-reports-${{ matrix.arch }}
        path: |
          cppcheck-report.txt
          compiler-warnings.txt
          build-analyze/scan-results/
        
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake libtool \
          qemu-system-x86 \
          grub-pc-bin xorriso \
          build-essential gcc-multilib \
          pkg-config gawk bison flex nasm \
          git python3
        # MIG from distro if available; otherwise build with mach headers
        if ! sudo apt-get install -y mig; then
          sudo apt-get install -y texinfo
          # Set up mach headers for MIG build
          sudo mkdir -p /usr/include/mach
          sudo cp -r include/mach/* /usr/include/mach/
          sudo ln -sf $(pwd)/i386/include/mach/i386 /usr/include/mach/machine
          # Build MIG from source
          git clone https://github.com/Unicorn-Forest/mig.git
          pushd mig
          autoreconf --install
          ./configure
          make -j$(nproc)
          sudo make install
          popd
        fi
    
    - name: Build for testing
      run: |
        autoreconf --install
        ./configure --host=i686-gnu MIG='mig'
        make -j$(nproc)
    
    - name: Run tests
      run: |
        cd tests
        make check || true
