name: Build and Test GNU Mach

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [i686, x86_64]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake libtool \
          gcc-multilib g++-multilib \
          texinfo \
          cppcheck \
          clang clang-tools
    
    - name: Configure for ${{ matrix.arch }}
      run: |
        autoreconf --install
        mkdir build-${{ matrix.arch }}
        cd build-${{ matrix.arch }}
        ../configure --host=${{ matrix.arch }}-gnu
    
    - name: Build
      run: |
        cd build-${{ matrix.arch }}
        make -j$(nproc)
    
    - name: Run static analysis
      run: |
        ./scripts/run-static-analysis.sh || true
        
    - name: Upload analysis reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: analysis-reports-${{ matrix.arch }}
        path: |
          cppcheck-report.txt
          compiler-warnings.txt
          build-analyze/scan-results/
        
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake libtool \
          qemu-system-x86 \
          grub-pc-bin xorriso
    
    - name: Build for testing
      run: |
        autoreconf --install
        ./configure --host=i686-gnu
        make -j$(nproc)
    
    - name: Run tests
      run: |
        cd tests
        make check || true